# -*- coding: utf-8 -*-
"""Prova DBSCAN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lNAbiaDutEPpuwW0lXlBeUtk_Yqj5KX
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_blobs

#Create synthetic datas that are similar to real datas
#elonged cluster, first fault (es Amatrice)
np.random.seed(42)
cluster_1 = np.random.normal(loc=[0.0], scale=[0.5, 3], size=(300, 2))
#shifted cluster, second fault (es Norcia)
cluster_2 = np.random.normal(loc=[3,5], scale=[1.5,1.5], size=(200,2))
#random noise (random earthquake)
noises = np.random.uniform(low=[-4,-5], high=[8, 5], size=(100,2))

#let's use all in a dataset
x = np.vstack([cluster_1, cluster_2, noises])

#let's use dbscan
db = DBSCAN(eps=0.5, min_samples=5).fit(x) #eps is distance and min_samples the neighbours
labels = db.labels_

#plot for the graphic
plt.figure(figsize=(8,6))

#Create the points colouring them based from the relative cluster
unique_labels = set(labels)
colors = [plt.cm.Spectral(each) for each in np.linspace(0, 1, len(unique_labels))]

for k, col in zip(unique_labels, colors):
  if k == -1:
    col = [0, 0, 0, 1]
    label_text = 'Noise (Background Seismicity)'
  else:
    label_text = f'Cluster {k} (Fault System)'

  class_member_mask = (labels == k)

  xy = x[class_member_mask]
  plt.plot(xy[:,0], xy[:, 1], 'o', markerfacecolor=tuple(col), markeredgecolor='k', markersize=8, label=label_text)

plt.title('DBSCAN application on synthetic seismic data', fontsize =14)
plt.xlabel('Latitude', fontsize = 12)
plt.ylabel('Longitude', fontsize = 12)
plt.legend()
plt.grid(True, linestyle='--', color='0.6')
plt.show()